[2022-06-08 11:30:51,623] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: spotify_dag.Whole_Spotify_ETL scheduled__2022-06-08T04:58:00+00:00 [queued]>
[2022-06-08 11:30:51,634] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: spotify_dag.Whole_Spotify_ETL scheduled__2022-06-08T04:58:00+00:00 [queued]>
[2022-06-08 11:30:51,635] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-08 11:30:51,635] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-08 11:30:51,635] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-08 11:30:51,699] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): Whole_Spotify_ETL> on 2022-06-08 04:58:00+00:00
[2022-06-08 11:30:51,705] {standard_task_runner.py:52} INFO - Started process 78289 to run task
[2022-06-08 11:30:51,709] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'spotify_dag', 'Whole_Spotify_ETL', 'scheduled__2022-06-08T04:58:00+00:00', '--job-id', '306', '--raw', '--subdir', 'DAGS_FOLDER/spotify_dag.py', '--cfg-path', '/tmp/tmpoa7mvs6v', '--error-file', '/tmp/tmp2dtarfl1']
[2022-06-08 11:30:51,711] {standard_task_runner.py:80} INFO - Job 306: Subtask Whole_Spotify_ETL
[2022-06-08 11:30:51,775] {task_command.py:370} INFO - Running <TaskInstance: spotify_dag.Whole_Spotify_ETL scheduled__2022-06-08T04:58:00+00:00 [running]> on host kubernetes-worker
[2022-06-08 11:30:51,888] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=wabuyajames@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=spotify_dag
AIRFLOW_CTX_TASK_ID=Whole_Spotify_ETL
AIRFLOW_CTX_EXECUTION_DATE=2022-06-08T04:58:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-08T04:58:00+00:00
[2022-06-08 11:30:51,890] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/james/airflowa/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/james/airflowa/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/james/airflow/dags/spotify_etl.py", line 49, in run_spotify_etl
    today = datetime.datetime.now()
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-06-08 11:30:51,899] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_dag, task_id=Whole_Spotify_ETL, execution_date=20220608T045800, start_date=20220608T083051, end_date=20220608T083051
[2022-06-08 11:30:51,954] {standard_task_runner.py:92} ERROR - Failed to execute job 306 for task Whole_Spotify_ETL (type object 'datetime.datetime' has no attribute 'datetime'; 78289)
[2022-06-08 11:30:52,004] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-08 11:30:52,224] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
